#
# Portable login environment
#

# Browser
if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

# Editors
export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'

# Language
if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

# Less
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# Source platform-specific config
if [[ "$OSTYPE" == darwin* ]]; then
  [[ -s "${ZDOTDIR:-$HOME}/.zprofile.mac" ]] && source "${ZDOTDIR:-$HOME}/.zprofile.mac"
elif [[ "$OSTYPE" == linux* ]]; then
  [[ -s "${ZDOTDIR:-$HOME}/.zprofile.linux" ]] && source "${ZDOTDIR:-$HOME}/.zprofile.linux"
fi

export PATH="$HOME/.elan/bin:$PATH"

# Added by Obsidian
export PATH="$PATH:/Applications/Obsidian.app/Contents/MacOS"
